"use client";
import React, { useState, useEffect } from 'react';
import { Card } from '../ui/card';
import { Button } from '../ui/button';
import { Dialog } from '../ui/dialog';
import { playTeacherSpeech, stopTeacherSpeech } from '@/lib/speech';
import { MarkdownRenderer } from '../ui/MarkdownRenderer';
import {
  ArrowLeft,
  Volume2,
  Sparkles,
  RotateCw,
  HelpCircle,
  BrainCircuit,
  Bot
} from 'lucide-react';
import { useAuth } from '@/context/AuthContext';
import { api } from '@/lib/api';

interface FlashcardCenterScreenProps {
  onNavigate: (screen: any) => void;
}

interface Flashcard {
  formula: string;
  title: string;
  def: string;
  deck: string;
  diagram?: string;
  isAutoGenerated?: boolean;
}

const defaultCards: Flashcard[] = [
  {
    formula: 'v = u + at',
    title: 'First Equation of Motion',
    def: 'Relates final velocity (v) to initial velocity (u), uniform acceleration (a), and elapsed time (t).',
    deck: 'Physics & Math Basics',
  },
  {
    formula: 'F = m · a',
    title: "Newton's Second Law",
    def: 'The force acting on an object is equal to the mass of the object multiplied by its acceleration.',
    deck: 'Physics & Math Basics',
  },
  {
    formula: '(a + b)² = a² + 2ab + b²',
    title: 'Square of a Binomial',
    def: 'The algebraic expansion of the sum of two variables squared.',
    deck: 'Physics & Math Basics',
  },
  {
    formula: 'a² + b² = c²',
    title: 'Pythagorean Theorem',
    def: 'In a right-angled triangle, the square of the hypotenuse side (c) is equal to the sum of squares of the other two perpendicular sides (a and b).',
    deck: 'Physics & Math Basics',
    diagram:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBaslXjc9BLKQk8XI-Zw5QnW-yy8_ISh6G9qpi1l_CwhAhUpXUsBW9Z6LIyWiNvpuKt7tYrbsLmMYIqFIeRa1jhvvYuCXLzBQXdedt7D-g-2-gQb6oln0wafVTukLiUFqXuEKhBd7eMc4-LJ4Pv3KIWG1ZG1ydmTOSPKNVNzu7GYz3FUod1Tx9p15RgNsecypFt_V7euzxZXym78iiqbAcblCkyzLZvf-2T4rtlC5xd7jGWW0EzeMa-',
  },
];

export function FlashcardCenterScreen({ onNavigate }: FlashcardCenterScreenProps) {
  const { updateUserXp } = useAuth();
  
  const [cards, setCards] = useState<Flashcard[]>(defaultCards);
  const [currentCardIndex, setCurrentCardIndex] = useState(0);
  const [isFlipped, setIsFlipped] = useState(false);
  const [isPlayingAudio, setIsPlayingAudio] = useState(false);
  
  const [aiModalOpen, setAiModalOpen] = useState(false);
  const [aiExplanation, setAiExplanation] = useState('');
  const [aiLoading, setAiLoading] = useState(false);
  
  const [showHint, setShowHint] = useState(false);
  const [hintText, setHintText] = useState('');
  const [hintLoading, setHintLoading] = useState(false);
  const [targetedLoading, setTargetedLoading] = useState(false);

  const currentCard = cards[currentCardIndex];

  // Auto-generation on Mount (Loophole Integration)
  useEffect(() => {
    // Simulate detecting a loophole from past tests and generating cards
    const fetchTargetedCards = async () => {
      setTargetedLoading(true);
      try {
        const res = await api.generateTargetedFlashcards({ topic: 'Fraction Operations & Isolation' });
        if (res?.cards && Array.isArray(res.cards)) {
          const generatedCards = res.cards.map((c: any) => ({
            ...c,
            deck: 'Auto-Generated Review',
            isAutoGenerated: true
          }));
          setCards(prev => [...generatedCards, ...prev]);
        }
      } catch (e) {
        console.warn('Could not auto-generate cards');
      } finally {
        setTargetedLoading(false);
      }
    };
    
    // Check if we already have generated cards in this session to prevent infinite fetching
    const hasGenerated = cards.some(c => c.isAutoGenerated);
    if (!hasGenerated) {
       fetchTargetedCards();
    }
  }, []);

  const handleAudio = () => {
    if (isPlayingAudio) {
      stopTeacherSpeech();
      setIsPlayingAudio(false);
      return;
    }
    
    setIsPlayingAudio(true);
    // Dynamically read the current card!
    const textToRead = `${currentCard.title}. The formula is: ${currentCard.formula}. Definition: ${currentCard.def}`;
    
    playTeacherSpeech(textToRead, {
      language: 'English',
      onStart: () => setIsPlayingAudio(true),
      onEnd: () => setIsPlayingAudio(false),
      onError: () => setIsPlayingAudio(false),
    });
  };

  const handleRating = (difficulty: 'hard' | 'good' | 'easy') => {
    updateUserXp(difficulty === 'easy' ? 15 : difficulty === 'good' ? 10 : 5);
    setIsFlipped(false);
    setShowHint(false);
    setAiExplanation(''); // Reset explanation for next card
    setCurrentCardIndex((prev) => (prev + 1) % cards.length);
  };

  const handleGenerateAiExplanation = async () => {
    setAiModalOpen(true);
    if (!aiExplanation) {
      setAiLoading(true);
      try {
        const res = await api.generateFlashcardExplanation({
          formula: currentCard.formula,
          title: currentCard.title,
          def: currentCard.def
        });
        setAiExplanation(res.explanation || 'Could not generate explanation.');
      } catch (e) {
        setAiExplanation('Oops, the AI teacher is offline. Try again later!');
      } finally {
        setAiLoading(false);
      }
    }
  };

  const handleSocraticHint = async (e: React.MouseEvent) => {
    e.stopPropagation();
    if (showHint || hintLoading) return;
    
    setHintLoading(true);
    try {
      const res = await api.getSocraticHint({
        question: `What is the formula and definition for ${currentCard.title}?`,
        context: 'Flashcard Socratic Quiz Mode'
      });
      setHintText(res.hint || 'Think about a real-world scenario where this applies!');
      setShowHint(true);
    } catch (e) {
      setHintText('Think carefully... what is the core concept here?');
      setShowHint(true);
    } finally {
      setHintLoading(false);
    }
  };

  if (!currentCard) return null;

  return (
    <div className="flex flex-col h-dvh overflow-hidden py-4 px-4 max-w-3xl mx-auto w-full">
      {/* Top Header */}
      <header className="shrink-0 py-2 border-b border-white/10 mb-4">
        <div className="flex items-center justify-between mb-3">
          <button
            onClick={() => onNavigate('dashboard')}
            className="flex items-center gap-2 text-xs md:text-sm text-slate-300 hover:text-white transition-colors cursor-pointer"
          >
            <ArrowLeft className="w-4 h-4" />
            <span>Back to Decks</span>
          </button>
          
          <h1 className="font-headline text-base md:text-lg font-bold text-amber-400 truncate max-w-[50%]">
            {currentCard.deck}
          </h1>
          
          <div className="flex items-center gap-1.5 px-3 py-1 rounded-full bg-teal-500/10 border border-teal-500/20 text-teal-300 text-xs">
            <span className="w-2 h-2 rounded-full bg-teal-400 animate-pulse" />
            <span className="hidden sm:inline">Offline Ready</span>
          </div>
        </div>

        {/* Progress bar */}
        <div>
          <div className="flex justify-between text-xs text-slate-400 mb-1">
            <span className="flex items-center gap-2">
              Progress
              {targetedLoading && (
                <span className="text-teal-400 animate-pulse flex items-center gap-1 text-[10px]">
                  <BrainCircuit className="w-3 h-3" /> Auto-generating weak spots...
                </span>
              )}
            </span>
            <span className="font-medium text-slate-200">
              Card {currentCardIndex + 1} of {cards.length}
            </span>
          </div>
          <div className="h-2 w-full bg-slate-900 rounded-full overflow-hidden border border-white/5">
            <div
              className="h-full bg-gradient-to-r from-amber-500 to-orange-500 rounded-full transition-all duration-300"
              style={{ width: `${((currentCardIndex + 1) / cards.length) * 100}%` }}
            />
          </div>
        </div>
      </header>

      {/* Main Flashcard Container */}
      <div className="flex-1 overflow-y-auto flex flex-col items-center justify-center pb-6">
        <div
          onClick={() => setIsFlipped(!isFlipped)}
          className={`w-full max-w-xl glass-card border-white/15 p-6 md:p-8 rounded-3xl cursor-pointer transition-all duration-300 relative group shadow-2xl min-h-[320px] flex flex-col justify-center items-center ${
            isFlipped ? 'border-amber-500/40 bg-slate-900/90' : 'hover:border-teal-500/40'
          }`}
        >
          {/* Badge for auto-generated cards */}
          {currentCard.isAutoGenerated && (
            <div className="absolute top-4 left-4 flex items-center gap-1 text-[10px] text-teal-300 bg-teal-950/50 px-2 py-1 rounded-lg border border-teal-500/30">
              <Bot className="w-3 h-3" /> Targeted Review
            </div>
          )}

          {/* Audio Pronunciation Button */}
          <button
            onClick={(e) => {
              e.stopPropagation();
              handleAudio();
            }}
            className={`absolute top-4 right-4 p-2.5 rounded-full border transition-all ${
              isPlayingAudio
                ? 'bg-amber-500 text-slate-950 border-amber-400 animate-pulse'
                : 'bg-slate-900/80 border-white/10 text-slate-300 hover:text-white hover:bg-slate-800'
            }`}
            title="Listen to card"
          >
            <Volume2 className="w-4 h-4" />
          </button>

          {!isFlipped ? (
            // FRONT OF CARD
            <div className="text-center w-full flex flex-col items-center justify-center">
              <h2 className="font-headline text-3xl md:text-4xl font-bold text-slate-200 tracking-wide mb-6">
                {currentCard.title}
              </h2>
              
              {/* Socratic Hint Area */}
              {showHint ? (
                <div className="mt-4 p-4 rounded-xl bg-teal-950/30 border border-teal-500/30 text-teal-100 text-sm italic max-w-sm animate-in fade-in">
                  💡 {hintText}
                </div>
              ) : (
                <button
                  onClick={handleSocraticHint}
                  disabled={hintLoading}
                  className="mt-4 px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 border border-white/10 text-slate-300 text-xs flex items-center gap-2 transition-colors disabled:opacity-50"
                >
                  {hintLoading ? (
                    <span className="w-4 h-4 border-2 border-slate-400 border-t-transparent rounded-full animate-spin" />
                  ) : (
                    <HelpCircle className="w-4 h-4 text-amber-400" />
                  )}
                  <span>Get Socratic Hint</span>
                </button>
              )}
              
              <div className="mt-8 text-[11px] text-slate-500 flex items-center justify-center gap-1">
                <RotateCw className="w-3 h-3" />
                <span>Tap anywhere to reveal answer</span>
              </div>
            </div>
          ) : (
            // BACK OF CARD
            <div className="text-center w-full animate-in fade-in slide-in-from-bottom-2">
              {/* Optional Diagram */}
              {currentCard.diagram && (
                <div className="w-full h-32 md:h-40 rounded-2xl bg-slate-950/70 border border-white/10 flex items-center justify-center mb-6 overflow-hidden p-2">
                  <img
                    src={currentCard.diagram}
                    alt={currentCard.title}
                    className="w-full h-full object-contain filter drop-shadow-lg"
                  />
                </div>
              )}
              
              <h2 className="font-headline text-3xl md:text-4xl font-bold text-amber-400 tracking-wide">
                {currentCard.formula}
              </h2>
              <div className="h-0.5 w-12 bg-amber-500/40 mx-auto my-3" />
              <p className="text-sm md:text-base text-slate-200 max-w-md mx-auto leading-relaxed pt-1">
                {currentCard.def}
              </p>
              
              {/* Generate AI Explanation link */}
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  handleGenerateAiExplanation();
                }}
                className="mt-6 mx-auto flex items-center justify-center gap-2 text-xs md:text-sm text-teal-400 hover:text-teal-300 transition-colors group px-3 py-1.5 rounded-lg hover:bg-teal-950/50"
              >
                <Sparkles className="w-4 h-4 group-hover:scale-110 transition-transform" />
                <span>Need an everyday analogy?</span>
              </button>
            </div>
          )}
        </div>

        {/* Spaced Repetition SRS Controls - Only visible when flipped */}
        {isFlipped && (
          <div className="w-full max-w-xl grid grid-cols-3 gap-3 mt-6 animate-in slide-in-from-bottom-4 fade-in">
            <button
              onClick={() => handleRating('hard')}
              className="flex flex-col items-center justify-center py-3 px-2 rounded-2xl border-2 border-rose-500/40 bg-rose-950/30 text-rose-300 hover:bg-rose-900/40 hover:border-rose-400 transition-all active:scale-95 cursor-pointer"
            >
              <span className="font-headline font-bold text-sm">Hard</span>
              <span className="text-[10px] text-slate-400 mt-0.5">&lt; 10 mins</span>
            </button>

            <button
              onClick={() => handleRating('good')}
              className="flex flex-col items-center justify-center py-3 px-2 rounded-2xl border-2 border-amber-500/50 bg-amber-950/30 text-amber-300 hover:bg-amber-900/40 hover:border-amber-400 transition-all active:scale-95 shadow-lg shadow-amber-950/40 scale-102 cursor-pointer"
            >
              <span className="font-headline font-bold text-sm">Good</span>
              <span className="text-[10px] text-amber-200/80 mt-0.5">Tomorrow</span>
            </button>

            <button
              onClick={() => handleRating('easy')}
              className="flex flex-col items-center justify-center py-3 px-2 rounded-2xl border-2 border-teal-500/40 bg-teal-950/30 text-teal-300 hover:bg-teal-900/40 hover:border-teal-400 transition-all active:scale-95 cursor-pointer"
            >
              <span className="font-headline font-bold text-sm">Easy</span>
              <span className="text-[10px] text-slate-400 mt-0.5">4 Days</span>
            </button>
          </div>
        )}
      </div>

      {/* AI Explanation Dialog */}
      <Dialog
        open={aiModalOpen}
        onOpenChange={setAiModalOpen}
        title={`Intuition: ${currentCard?.title}`}
        description="Everyday analogy to make this concept crystal clear."
      >
        <div className="p-4 rounded-2xl bg-slate-950/80 border border-teal-500/30 text-sm text-slate-200 leading-relaxed space-y-3">
          {aiLoading ? (
            <div className="flex items-center justify-center py-6 gap-2 text-slate-400">
              <span className="w-4 h-4 border-2 border-teal-400 border-t-transparent rounded-full animate-spin" />
              <span>Generating intuitive real-world explanation...</span>
            </div>
          ) : (
            <MarkdownRenderer content={aiExplanation} />
          )}
        </div>
      </Dialog>
    </div>
  );
}
